project:
  type: website

lang: zh

website:
  description: "A blog built with Quarto"
  site-url: https://blog.robinye.cn
  title: "RobinYe's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    toc: true
    theme:
      light: [cosmo, brand]
      dark: [darkly, brand]
    respect-user-color-scheme: true
    css: styles.css



